
language: csharp
solution: FbxSharpBuild.sln

sudo: false

addons:
  apt:
    packages:
      - nunit-console

script:
  - ./build.sh

deploy:
  skip_cleanup: true
  provider: script
  script: ./nuget-pack-push.sh
  on:
    tags: true
